CREATE TABLE IF NOT EXISTS impedance (
  impedance_uid UUID NOT NULL PRIMARY KEY,
  source VARCHAR NOT NULL,
  piston_diameter VARCHAR NOT NULL,
  resonance_frequency VARCHAR NOT NULL,
  dc_resistance VARCHAR NOT NULL,
  ac_resistance VARCHAR NOT NULL,
  mechanical_damping VARCHAR NOT NULL,
  electrical_damping VARCHAR NOT NULL,
  total_damping VARCHAR NOT NULL,
  equivalence_compliance VARCHAR NOT NULL,
  voice_coil_inductance VARCHAR NOT NULL,
  efficiency VARCHAR NOT NULL,
  sensitivity VARCHAR NOT NULL,
  cone_mass VARCHAR NOT NULL,
  suspension_compliance VARCHAR NOT NULL,
  force_factor VARCHAR NOT NULL,
  kr VARCHAR NOT NULL,
  xr VARCHAR NOT NULL,
  ki VARCHAR NOT NULL,
  xi VARCHAR NOT NULL,
  cabinet_uid UUID NOT NULL,
  frequencies JSONB NOT NULL,
  highest_frequency FLOAT NOT NULL,
  lowest_frequency FLOAT NOT NULL,
  impedances JSONB NOT NULL,
  phases JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  FOREIGN KEY (cabinet_uid) REFERENCES cabinet(cabinet_uid) ON DELETE CASCADE ON UPDATE CASCADE
);