version: '2.4'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    build:
      context: .
      dockerfile: db.Dockerfile
    env_file:
      - .env
    volumes:
      - 'asb-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  app:
    image: app:latest
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '8000:8000'
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/cerbot
  certbot:
    image: certbot/certbot
    container_name: certtbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/cerbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email victor@anechoic-station.berlin.com -d anechoic-station.berlin.com --agree-tos

volumes:
  asb-data: