version: '2.4'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - /var/www/shared/env/.env
    volumes:
      - /var/www/backend/docker/sql:/docker-entrypoint-initdb.d
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  app:
    image: app:latest
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      -  /var/www/shared/env/.env
    depends_on:
      - postgres
    ports:
      - '8000:8000'

volumes:
  postgres: