version: '2.4'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - app_network
    env_file:
      - .env
    volumes:
      - 'asb-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  backend:
    image: asb-app:latest
    container_name: asb-app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_network
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '8000:8000'

volumes:
  asb-data:

networks:
  app_network:
    driver: bridge