version: '3.4'
services:
  app:
    image: app:latest
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      -  /var/www/shared/env/.env
    ports:
      - '8000:8000'